### PR TITLE
Polish worldmap functionality.

### PR DESCRIPTION
**Pull request by GraionDilach**
[image](https://user-images.githubusercontent.com/1136302/217333472-5d35e6e2-2be8-43d6-b169-533a572d090f.png)

Depends on https://github.com/SpellholdStudios/BP-BGT-Worldmap/pull/33 and marked as draft until the other one hits a release.

### CODE REVIEW

**Comment by GraionDilach** [comment]
TODO: Test and potentially handle Fishing for Trouble.

**Comment by GraionDilach** [comment]
Awaits next version of Worldmap which includes the icon image.

**Comment by ALIENQuake** [comment]
@GraionDilach The depends on Worldmap PR was merged, we are good to go with this one?

**Comment by GraionDilach** [comment]
@ALIENQuake I acknowledge I haven't tested if it crashes the game, but the image index this PR utilizes is a nonexistant frame in BP-BGT Worldmap v11.0, which is the latest stable. I kept this in draft to ensure the dependency hits a stable first.

It is ready otherwise and my reasoning is moreso praactical than technical afterall.

**Comment by GraionDilach** [comment]
Ready for merge, now that BP-BGT Worldmap 12.0 is out.

**Comment by Gitjas** [comment]
Let me know if I should tagg a new release.

**Comment by GraionDilach** [comment]
@Austin-BG ?

**Comment by Austin-BG** [comment]
Thank you! There are quite a lot of changes to the mod, and I plan to add them this weekend too, so that version 14.3 will be released with several fixes at once. I'll let Jastey know when it's ready!

**Pull request merged**
